### ISSUE TITLE
Support objects for weighted sampling?

### ISSUE THREAD

**Issue by jbilcke** [Yomguithereal/pandemonium#2]
Example usage:

```js
import {sample} from 'pandemonium';
sample({
    apple: 10,
    orange: 8,
    pear: 1
});
>>> 'orange'
```

Example implementation: https://github.com/substack/node-deck/blob/master/index.js

**Comment by Yomguithereal** [comment]
Sure, this would be nice to have. A version taking only a list of weight would be nice (plus you need to know if you have relative weights to avoid a `O(n)` pass before or not.

Reservoir sampling would also be cool.

Do you want to create a PR to add the function?

**Comment by Yomguithereal** [comment]
@jbilcke I just added the `weightedChoice` and `weightedRandomIndex` functions.
